apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dummy
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dummy-deploy
  targetCPUUtilizationPercentage: 50
